// Generates firebase.js from environment variables.
// Local dev: create a .env file (see .env.example), then run: node build.js
// Vercel: add vars in Project Settings → Environment Variables

const fs = require('fs');

// Minimal .env loader (no dependencies needed)
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf8')
    .split('\n')
    .forEach(line => {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) return;
      const eq = trimmed.indexOf('=');
      if (eq < 0) return;
      const key = trimmed.slice(0, eq).trim();
      const val = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) process.env[key] = val;
    });
}

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('❌ Missing env vars:', missing.join(', '));
  console.error('   Copy .env.example → .env and fill in your Firebase credentials.');
  process.exit(1);
}

const output = `// Auto-generated by build.js — do not edit or commit this file
const firebaseConfig = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_AUTH_DOMAIN}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET}",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}"
};

firebase.initializeApp(firebaseConfig);
const db = firebase.firestore();
const DOC_REF = db.collection('dbh26').doc('sumut');
`;

fs.writeFileSync('firebase.js', output);
console.log('✅ firebase.js generated from environment variables');
